project="LEEF"
title="Luanti Extended Engine Features"
description="Luanti Extended Engine Features collection index"
format="markdown"
backtick_references=false
file = {
   "./LEEF-b3d",
   "./LEEF-class",
   "./LEEF-filesystem",
   "./LEEF-math/modules",
   exclude = {
      "./LEEF-class/init.lua",
      "./LEEF-b3d/init.lua",
      "./LEEF-filesystem/init.lua"
   }
}
dir="./docs"
style="!new"
no_lua_ref=true